return function(colors)
    return {
        -- CmpItemKindClass = { link = "Type" },
        -- CmpItemKindConstant = { link = "Constant" },
        -- CmpItemKindConstructor = { link = "TSConstructor" },
        -- CmpItemKindFunction = { link = "Function" },
        -- CmpItemKindKeyword = { link = "Keyword" },
        -- CmpItemKindOperator = { link = "Operator" },
        -- CmpItemKindProperty = { link = "TSProperty" },
        -- CmpItemKindStruct = { link = "Structure" },
        -- CmpItemKindTypeParameter = { link = "TSParameter" },
        -- CmpItemKindUnit = { link = "Number" },
        -- CmpItemKindValue = { link = "String" },
        -- CmpItemKindVariable = { link = "Identifier" },
        CmpDocumentationBorder = { fg = colors.darker_black, bg = colors.darker },
        CmpItemAbbr = { fg = colors.white, bg = colors.darker_black },
        CmpItemAbbrDeprecated = { fg = colors.green, bg = colors.darker_black },
        CmpItemAbbrMatch = { fg = colors.white, bg = colors.darker_black },
        CmpItemAbbrMatchFuzzy = { fg = colors.white, bg = colors.darker_black },
        CmpItemKind = { fg = colors.blue, bg = colors.darker_black },
        CmpItemMenu = { fg = colors.green, bg = colors.darker_black },
        Pmenu = { fg = colors.white, bg = colors.darker_black },
        PmenuSel = { fg = colors.darker_black, bg = colors.blue, bold = true, italic = true },
        PmenuBorder = { fg = colors.darker_black, bg = colors.darker_black },
        PmenuSbar = { bg = colors.darker_black },
        PmenuThumb = { bg = colors.blue },

        CmpItemKindConstant = { fg = colors.base09 },
        CmpItemKindFunction = { fg = colors.base0D },
        CmpItemKindIdentifier = { fg = colors.base08 },
        CmpItemKindField = { fg = colors.base08 },
        CmpItemKindVariable = { fg = colors.base0E },
        CmpItemKindSnippet = { fg = colors.red },
        CmpItemKindText = { fg = colors.base0B },
        CmpItemKindStructure = { fg = colors.base0E },
        CmpItemKindType = { fg = colors.base0A },
        CmpItemKindKeyword = { fg = colors.base07 },
        CmpItemKindMethod = { fg = colors.base0D },
        CmpItemKindConstructor = { fg = colors.blue },
        CmpItemKindFolder = { fg = colors.base07 },
        CmpItemKindModule = { fg = colors.base0A },
        CmpItemKindProperty = { fg = colors.base08 },
        CmpItemKindEnum = { fg = colors.blue },
        CmpItemKindUnit = { fg = colors.base0E },
        CmpItemKindClass = { fg = colors.teal },
        CmpItemKindFile = { fg = colors.base07 },
        CmpItemKindInterface = { fg = colors.green },
        CmpItemKindColor = { fg = colors.white },
        CmpItemKindReference = { fg = colors.base05 },
        CmpItemKindEnumMember = { fg = colors.purple },
        CmpItemKindStruct = { fg = colors.base0E },
        CmpItemKindValue = { fg = colors.cyan },
        CmpItemKindEvent = { fg = colors.yellow },
        CmpItemKindOperator = { fg = colors.base05 },
        CmpItemKindTypeParameter = { fg = colors.base08 },
        CmpItemKindCopilot = { fg = colors.green },
    }
end
