return function(colors)
    return {
        DevIconDefault = { fg = colors.red, bg = colors.black },
        DevIconC = { fg = colors.blue, bg = colors.black },
        DevIconCpp = { fg = colors.blue, bg = colors.black },
        DevIconCss = { fg = colors.blue, bg = colors.black },
        DevIcondeb = { fg = colors.cyan, bg = colors.black },
        DevIconDockerfile = { fg = colors.cyan, bg = colors.black },
        DevIconHtml = { fg = colors.baby_pink, bg = colors.black },
        DevIconJpeg = { fg = colors.dark_purple, bg = colors.black },
        DevIconJpg = { fg = colors.dark_purple, bg = colors.black },
        DevIconjs = { fg = colors.sun, bg = colors.black },
        DevIconkt = { fg = colors.orange, bg = colors.black },
        DevIconLock = { fg = colors.red, bg = colors.black },
        DevIconLua = { fg = colors.blue, bg = colors.black },
        DevIconmp3 = { fg = colors.white, bg = colors.black },
        DevIconmp4 = { fg = colors.white, bg = colors.black },
        DevIconout = { fg = colors.white, bg = colors.black },
        DevIconPng = { fg = colors.dark_purple, bg = colors.black },
        DevIconPy = { fg = colors.cyan, bg = colors.black },
        DevIconToml = { fg = colors.blue, bg = colors.black },
        DevIconTs = { fg = colors.teal, bg = colors.black },
        DevIconttf = { fg = colors.white, bg = colors.black },
        DevIconRb = { fg = colors.pink, bg = colors.black },
        DevIconrpm = { fg = colors.orange, bg = colors.black },
        DevIconVue = { fg = colors.vibrant_green, bg = colors.black },
        DevIconwoff = { fg = colors.white, bg = colors.black },
        DevIconwoff2 = { fg = colors.white, bg = colors.black },
        DevIconxz = { fg = colors.sun, bg = colors.black },
        DevIconzip = { fg = colors.sun, bg = colors.black },
        DevIconZig = { fg = colors.orange, bg = colors.black },
        DevIconMd = { fg = colors.blue, bg = colors.black },
        DevIconTsx = { fg = colors.blue, bg = colors.black },
        DevIconJsx = { fg = colors.blue, bg = colors.black },
        DevIconSvelte = { fg = colors.red, bg = colors.black },
        DevIconJava = { fg = colors.orange, bg = colors.black },
        DevIconDart = { fg = colors.cyan, bg = colors.black }
    }
end
