return {
	override = {
		deb = { icon = "", name = "Deb" },
		Dockerfile = { icon = "", name = "Dockerfile" },
		md = { icon = "", name = "Md" },
		jpeg = { icon = "", name = "JPEG" },
		jpg = { icon = "", name = "JPG" },
		png = { icon = "", name = "PNG" },
		ts = { icon = "󰛦", name = "TS" },
		lock = { icon = "󰌾", name = "Lock" },
		mp3 = { icon = "󰎈", name = "MP3" },
		mp4 = { icon = "", name = "MP4" },
		out = { icon = "", name = "Out" },
		toml = { icon = "", name = "TOML" },
		yuck = { icon = "󰇷", name = "Yuck" },
		vim = { icon = "", name = "Vim" },
		rpm = { icon = "", name = "RPM" },
		ttf = { icon = "", name = "TrueTypeFont" },
		woff = { icon = "", name = "WebOpenFontFormat" },
		woff2 = { icon = "", name = "WebOpenFontFormat2" },
		xz = { icon = "", name = "XZ" },
		zip = { icon = "", name = "Zip" },
	},
	default = true,
}
