local colors = require("tevim.themes").getCurrentTheme()
local utils = require("tevim.core.utils")

return {
	CmpDocumentationBorder = { fg = colors.darker, bg = colors.darker },
	CmpItemAbbr = { fg = colors.foreground, bg = colors.darker },
	CmpItemAbbrDeprecated = { fg = colors.green, bg = colors.darker },
	CmpItemAbbrMatch = { fg = colors.foreground, bg = colors.darker, bold = true },
	CmpItemAbbrMatchFuzzy = { fg = colors.foreground, bg = colors.darker, bold = true },
	CmpItemKind = { fg = colors.blue, bg = colors.darker },
	CmpItemMenu = { fg = colors.green, bg = colors.darker },
	CmpNormal = { fg = colors.foreground, bg = colors.darker },
	CmpBorder = { fg = colors.darker, bg = colors.darker },
	CmpSelection = { fg = colors.darker, bg = colors.blue, bold = true, italic = true },

	CmpItemKindConstant = { fg = colors.base09 },
	CmpItemKindFunction = { fg = colors.base0D },
	CmpItemKindIdentifier = { fg = colors.base08 },
	CmpItemKindField = { fg = colors.base08 },
	CmpItemKindVariable = { fg = colors.base0E },
	CmpItemKindSnippet = { fg = colors.base0A },
	CmpItemKindText = { fg = colors.base0B },
	CmpItemKindStructure = { fg = colors.base0E },
	CmpItemKindType = { fg = colors.base0A },
	CmpItemKindKeyword = { fg = colors.base09 },
	CmpItemKindMethod = { fg = colors.base0D },
	CmpItemKindConstructor = { fg = colors.base0C },
	CmpItemKindFolder = { fg = colors.base07 },
	CmpItemKindFile = { fg = colors.base07 },
	CmpItemKindModule = { fg = colors.base0A },
	CmpItemKindProperty = { fg = colors.base08 },
	CmpItemKindEnum = { fg = colors.base0C },
	CmpItemKindUnit = { fg = colors.base0E },
	CmpItemKindClass = { fg = colors.base0C },
	CmpItemKindInterface = { fg = colors.base0A },
	CmpItemKindColor = { fg = colors.foreground },
	CmpItemKindReference = { fg = colors.base05 },
	CmpItemKindEnumMember = { fg = colors.base0E },
	CmpItemKindStruct = { fg = colors.base0E },
	CmpItemKindValue = { fg = colors.base0B },
	CmpItemKindEvent = { fg = colors.base0E },
	CmpItemKindOperator = { fg = colors.base05 },
	CmpItemKindTypeParameter = { fg = colors.base08 },
	CmpItemKindCopilot = { fg = colors.green },
	CmpItemKindCodeium = { fg = utils.mix(colors.red, colors.green, 0.5) },

	-- AI
	CopilotSuggestion = { fg = utils.blend(colors.foreground, colors.background, 0.2), italic = true },
	TabnineSuggestion = { link = "CopilotSuggestion" },
}
