local colors = require("tevim.themes").getCurrentTheme()

return {
	CmpDocumentationBorder = { fg = colors.darker_black, bg = colors.darker },
	CmpItemAbbr = { fg = colors.white, bg = colors.darker_black },
	CmpItemAbbrDeprecated = { fg = colors.green, bg = colors.darker_black },
	CmpItemAbbrMatch = { fg = colors.white, bg = colors.darker_black, bold = true },
	CmpItemAbbrMatchFuzzy = { fg = colors.white, bg = colors.darker_black, bold = true },
	CmpItemKind = { fg = colors.blue, bg = colors.darker_black },
	CmpItemMenu = { fg = colors.green, bg = colors.darker_black },
	CmpNormal = { fg = colors.white, bg = colors.darker_black },
	CmpBorder = { fg = colors.darker_black, bg = colors.darker_black },
	CmpSelection = { fg = colors.darker_black, bg = colors.blue, bold = true, italic = true },

	CmpItemKindConstant = { fg = colors.base09 },
	CmpItemKindFunction = { fg = colors.base0D },
	CmpItemKindIdentifier = { fg = colors.base08 },
	CmpItemKindField = { fg = colors.base08 },
	CmpItemKindVariable = { fg = colors.base0E },
	CmpItemKindSnippet = { fg = colors.red },
	CmpItemKindText = { fg = colors.base0B },
	CmpItemKindStructure = { fg = colors.base0E },
	CmpItemKindType = { fg = colors.base0A },
	CmpItemKindKeyword = { fg = colors.base09 },
	CmpItemKindMethod = { fg = colors.base0D },
	CmpItemKindConstructor = { fg = colors.blue },
	CmpItemKindFolder = { fg = colors.base07 },
	CmpItemKindFile = { fg = colors.base07 },
	CmpItemKindModule = { fg = colors.base0A },
	CmpItemKindProperty = { fg = colors.base08 },
	CmpItemKindEnum = { fg = colors.blue },
	CmpItemKindUnit = { fg = colors.base0E },
	CmpItemKindClass = { fg = colors.teal },
	CmpItemKindInterface = { fg = colors.green },
	CmpItemKindColor = { fg = colors.white },
	CmpItemKindReference = { fg = colors.base05 },
	CmpItemKindEnumMember = { fg = colors.purple },
	CmpItemKindStruct = { fg = colors.base0E },
	CmpItemKindValue = { fg = colors.cyan },
	CmpItemKindEvent = { fg = colors.yellow },
	CmpItemKindOperator = { fg = colors.base05 },
	CmpItemKindTypeParameter = { fg = colors.base08 },
	CmpItemKindCopilot = { fg = colors.green },
	CmpItemKindCodeium = { fg = colors.yellow },

	-- Copilot.vim
	CopilotSuggestion = { fg = colors.light_grey, italic = true },
}
