local colors = require("tevim.themes").getCurrentTheme()
local utils = require("tevim.core.utils")

return {
	DevIconDefault = { fg = colors.red },
	DevIconC = { fg = colors.blue },
	DevIconCpp = { fg = colors.blue },
	DevIconCSS = { fg = colors.blue },
	DevIcondeb = { fg = utils.mix(colors.foreground, colors.blue, 0.7) },
	DevIconDockerfile = { fg = utils.mix(colors.foreground, colors.blue, 0.7) },
	DevIconHtml = { fg = colors.red },
	DevIconJpeg = { fg = utils.mix(colors.red, colors.blue, 0.5) },
	DevIconJpg = { fg = utils.mix(colors.red, colors.blue, 0.5) },
	DevIconJs = { fg = utils.mix(colors.red, colors.green, 0.5) },
	DevIconKotlin = { fg = utils.mix(colors.red, colors.blue, 0.5) },
	DevIconLock = { fg = colors.red },
	DevIconLua = { fg = colors.blue },
	DevIconmp3 = { fg = colors.foreground },
	DevIconmp4 = { fg = colors.foreground },
	DevIconout = { fg = colors.foreground },
	DevIconPng = { fg = utils.mix(colors.red, colors.blue, 0.5) },
	DevIconPy = { fg = utils.mix(colors.foreground, colors.blue, 0.7) },
	DevIconToml = { fg = colors.blue },
	DevIconTs = { fg = colors.blue },
	DevIconttf = { fg = colors.foreground },
	DevIconRb = { fg = colors.red },
	DevIconrpm = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5) },
	DevIconVue = { fg = colors.green },
	DevIconwoff = { fg = colors.foreground },
	DevIconwoff2 = { fg = colors.foreground },
	DevIconxz = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5) },
	DevIconzip = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5) },
	DevIconZig = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5) },
	DevIconMd = { fg = colors.blue },
	DevIconTsx = { fg = colors.blue },
	DevIconJsx = { fg = colors.blue },
	DevIconSvelte = { fg = colors.red },
	DevIconJava = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5) },
	DevIconDart = { fg = utils.mix(colors.foreground, colors.blue, 0.7) },
	DevIconVim = { fg = colors.green },
	DevIconLicense = { fg = utils.mix(colors.red, colors.green, 0.5) },
	DevIconNix = { fg = colors.blue },
	DevIconGitIgnore = { fg = colors.red },
	DevIconSh = { fg = colors.green },
	DevIconGitlabCI = { fg = colors.red },
}
