local colors = require("tevim.themes").getCurrentTheme()

return {
	DevIconDefault = { fg = colors.red },
	DevIconC = { fg = colors.blue },
	DevIconCpp = { fg = colors.blue },
	DevIconCSS = { fg = colors.blue },
	DevIcondeb = { fg = colors.cyan },
	DevIconDockerfile = { fg = colors.cyan },
	DevIconHtml = { fg = colors.red },
	DevIconJpeg = { fg = colors.purple },
	DevIconJpg = { fg = colors.purple },
	DevIconjs = { fg = colors.orange },
	DevIconkt = { fg = colors.orange },
	DevIconLock = { fg = colors.red },
	DevIconLua = { fg = colors.blue },
	DevIconmp3 = { fg = colors.white },
	DevIconmp4 = { fg = colors.white },
	DevIconout = { fg = colors.white },
	DevIconPng = { fg = colors.purple },
	DevIconPy = { fg = colors.cyan },
	DevIconToml = { fg = colors.blue },
	DevIconTs = { fg = colors.blue },
	DevIconttf = { fg = colors.white },
	DevIconRb = { fg = colors.red },
	DevIconrpm = { fg = colors.orange },
	DevIconVue = { fg = colors.green },
	DevIconwoff = { fg = colors.white },
	DevIconwoff2 = { fg = colors.white },
	DevIconxz = { fg = colors.orange },
	DevIconzip = { fg = colors.orange },
	DevIconZig = { fg = colors.orange },
	DevIconMd = { fg = colors.blue },
	DevIconTsx = { fg = colors.blue },
	DevIconJsx = { fg = colors.blue },
	DevIconSvelte = { fg = colors.red },
	DevIconJava = { fg = colors.orange },
	DevIconDart = { fg = colors.cyan },
	DevIconVim = { fg = colors.green },
}
