local colors = require("tevim.themes").getCurrentTheme()

return {
	NavicIconsConstant = { fg = colors.base09 },
	NavicIconsFunction = { fg = colors.base0D },
	NavicIconsIdentifier = { fg = colors.base08 },
	NavicIconsField = { fg = colors.base08 },
	NavicIconsVariable = { fg = colors.base0E },
	NavicIconsSnippet = { fg = colors.red },
	NavicIconsText = { fg = colors.base0B },
	NavicIconsStructure = { fg = colors.base0E },
	NavicIconsType = { fg = colors.base0A },
	NavicIconsKeyword = { fg = colors.base07 },
	NavicIconsMethod = { fg = colors.base0D },
	NavicIconsConstructor = { fg = colors.blue },
	NavicIconsFolder = { fg = colors.base07 },
	NavicIconsModule = { fg = colors.base0A },
	NavicIconsProperty = { fg = colors.base08 },
	NavicIconsEnum = { fg = colors.blue },
	NavicIconsUnit = { fg = colors.base0E },
	NavicIconsClass = { fg = colors.teal },
	NavicIconsFile = { fg = colors.base07 },
	NavicIconsInterface = { fg = colors.green },
	NavicIconsColor = { fg = colors.white },
	NavicIconsReference = { fg = colors.base05 },
	NavicIconsEnumMember = { fg = colors.purple },
	NavicIconsStruct = { fg = colors.base0E },
	NavicIconsValue = { fg = colors.cyan },
	NavicIconsEvent = { fg = colors.yellow },
	NavicIconsOperator = { fg = colors.base05 },
	NavicIconsTypeParameter = { fg = colors.base08 },
	NavicIconsNamespace = { fg = colors.teal },
	NavicIconsPackage = { fg = colors.green },
	NavicIconsString = { fg = colors.green },
	NavicIconsNumber = { fg = colors.pink },
	NavicIconsBoolean = { fg = colors.orange },
	NavicIconsArray = { fg = colors.blue },
	NavicIconsObject = { fg = colors.base0E },
	NavicIconsKey = { fg = colors.red },
	NavicIconsNull = { fg = colors.cyan },
	NavicText = { fg = colors.light_grey },
	NavicSeparator = { fg = colors.red },
}
