local colors = require("tevim.themes").getCurrentTheme()

return {
	TodoBgFix = { fg = colors.black2, bg = colors.red, bold = true },
	TodoBgHack = { fg = colors.black2, bg = colors.yellow, bold = true },
	TodoBgNote = { fg = colors.black2, bg = colors.white, bold = true },
	TodoBgPerf = { fg = colors.black2, bg = colors.purple, bold = true },
	TodoBgTest = { fg = colors.black2, bg = colors.green, bold = true },
	TodoBgTodo = { fg = colors.black2, bg = colors.blue, bold = true },
	TodoBgWarn = { fg = colors.black2, bg = colors.orange, bold = true },
	TodoFgFix = { fg = colors.red },
	TodoFgHack = { fg = colors.yellow },
	TodoFgNote = { fg = colors.white },
	TodoFgPerf = { fg = colors.purple },
	TodoFgTest = { fg = colors.green },
	TodoFgTodo = { fg = colors.blue },
	TodoFgWarn = { fg = colors.orange },
	TodoSignFix = { link = "TodoFgFix" },
	TodoSignHack = { link = "TodoFgHack" },
	TodoSignNote = { link = "TodoFgNote" },
	TodoSignPerf = { link = "TodoFgPerf" },
	TodoSignTest = { link = "TodoFgTest" },
	TodoSignTodo = { link = "TodoFgTodo" },
	TodoSignWarn = { link = "TodoFgWarn" },
}
