local colors = require("tevim.themes").getCurrentTheme()

return {
	TroubleCount = { fg = colors.pink },
	TroubleCode = { fg = colors.white },
	TroubleWarning = { fg = colors.orange },
	TroubleSignWarning = { fg = colors.yellow },
	TroubleTextWarning = { fg = colors.white },
	TroublePreview = { fg = colors.red },
	TroubleSource = { fg = colors.cyan },
	TroubleSignHint = { fg = colors.green },
	TroubleTextHint = { fg = colors.red },
	TroubleHint = { fg = colors.orange },
	TroubleSignOther = { fg = colors.green },
	TroubleSignInformation = { fg = colors.white },
	TroubleTextInformation = { fg = colors.blue },
	TroubleInformation = { fg = colors.white },
	TroubleError = { fg = colors.red },
	TroubleTextError = { fg = colors.red },
	TroubleSignError = { fg = colors.red },
	TroubleText = { fg = colors.white },
	TroubleFile = { fg = colors.yellow },
	TroubleFoldIcon = { fg = colors.cyan },
	TroubleNormal = { fg = colors.white },
	TroubleLocation = { fg = colors.red },
	TroubleIndent = { link = "Comment" },
}
